### PR TITLE
Add jenkinsfile

### PR DESCRIPTION
**Pull request by tarnawski**
Ready. All of you should see result in our Jenkins.

### CODE REVIEW

**Comment by tarnawski** [comment]
Needs work. I will do it soon and share the results.

**Comment by partikus** [comment]
@tarnawski well done! thanks 
btw. we were testing `dir('taskmanager')` statement but there were a lot of issues so the current version look really nice and works fine!

**Review by partikus — DISMISSED** [review]

**Comment by partikus** [comment]
would be great to take care about workspace clean up
```
stage('Clean up') {
    deleteDir()
}
```

**Comment by dominikhajduk** [comment]
@tarnawski for me looks fine 👍  Will try add travis with same level of tests.

**Review by dominikhajduk — DISMISSED** [review]

**Comment by tarnawski** [comment]
Add step to clean workspace. Please check  again.

**Review by partikus — APPROVED** [review]

**Comment by partikus** [comment]
@tarnawski good job!

**Pull request merged**
